# Generated by Django 2.0.2 on 2018-03-07 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='user',
        ),
    ]
