# Generated by Django 2.0.2 on 2018-03-17 00:32
# flake8: noqa

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180315_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sideproject',
            name='name',
            field=models.CharField(max_length=25, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='sideproject',
            name='url',
            field=models.URLField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='sideproject',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
