# Generated by Django 2.0.2 on 2018-03-19 20:13
# flake8: noqa

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='filled_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
