# Generated by Django 2.0.2 on 2018-04-07 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0008_auto_20180406_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='position',
            name='filled_by',
        ),
        migrations.AddField(
            model_name='position',
            name='filled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Position'),
        ),
        migrations.AddField(
            model_name='position',
            name='applicants',
            field=models.ManyToManyField(through='projects.Application', to=settings.AUTH_USER_MODEL),
        ),
    ]
