# Generated by Django 2.0.2 on 2018-04-13 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0011_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='filled',
        ),
        migrations.AddField(
            model_name='position',
            name='filled_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filled', to=settings.AUTH_USER_MODEL),
        ),
    ]
